---
title: "Eindopdracht"
author: "Muniru & Sam"
date: '2022-06-03'
output:
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
  pdf_document:
    toc: yes
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(deSolve)
library(pracma)
library(plotly)
r <- 0.11
rho <- 1.29
c <- 0.5

parameters <- c(m = 0.445, k = (1/2) * c * rho * (pi * r^2),
                mu = 0.1, g = c(y = 0, z = -9.81))

v <- 30
state_straight <- c(velocity = c(y = v*cos(30*pi/180), z = v*sin(30*pi/180)),
                    position = c(y = 0, z = 0))

times <- seq(0, 10, by = 0.01)

model <- function(t, y, parms){
  with(as.list(c(y, parms)), {
    g <- c(g.y, g.z)
    velocity <- c(velocity.y, velocity.z)
    position <- c(position.y, position.z)
    
    acc <-  (m * g - k * velocity * sqrt(velocity.y^2 + velocity.z^2)) / m 
    
    return(list(c(acc, velocity)))
  }
  )
}


out <- as.data.frame(ode(times = times, y = state_straight, parms = parameters, func = model, method = "euler"))
output <- subset(out, position.z >= 0)
output$position.x <- rep(0, length(output$time))

plot(output$position.x, output$position.y, type = "l")
fig <- plot_ly(output, x = ~position.x, y = ~position.y, z = ~position.z, type = 'scatter3d', mode = 'lines',
        opacity = 1)

ratio <- max(output$position.z) / max(output$position.y)
      
fig <- fig %>% layout(scene = list(aspectratio = list(x = 1, y = 1, z = ratio)))

fig
```